# Generated by Django 3.2 on 2025-12-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='菜品描述'),
        ),
    ]
