# Generated by Django 3.2 on 2025-12-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='接单联系人'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='接单联系电话'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='小计'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/img/dish/', verbose_name='菜品图片'),
        ),
    ]
